name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        laravel: [ 12.*, 11.*, 10.*, 9.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: "10.*"
            testbench: "^8.21"
            carbon: "^2.67"
          - laravel: "11.*"
            testbench: "9.*"
            carbon: "^3.0"
          - laravel: "12.*"
            testbench: "10.*"
            carbon: "^3.0"
        exclude:
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*

    name: Tests P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-L${{ matrix.laravel }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, mbstring, zip, fileinfo
        coverage: none

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Integration Tests
      run: php ./vendor/bin/pest
